# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColRelation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('table_id', models.IntegerField()),
                ('col_id', models.IntegerField()),
                ('relation', models.CharField(max_length=255)),
                ('verdict', models.IntegerField()),
            ],
            options={
                'db_table': 'col_relation',
            },
        ),
#        migrations.CreateModel(
#            name='DjangoMigrations',
#            fields=[
#                ('id', models.IntegerField(primary_key=True, serialize=False)),
#                ('app', models.CharField(max_length=255)),
#                ('name', models.CharField(max_length=255)),
#                ('applied', models.DateTimeField()),
#            ],
#            options={
#                'db_table': 'django_migrations',
#            },
#        ),
        migrations.CreateModel(
            name='FuzzyMatch',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('row', models.IntegerField()),
                ('col', models.IntegerField()),
                ('table_id', models.IntegerField()),
                ('entity_id', models.IntegerField()),
            ],
            options={
                'db_table': 'fuzzy_match',
            },
        ),
        migrations.CreateModel(
            name='GoldAnnotation',
            fields=[
                ('table_id', models.IntegerField(primary_key=True, serialize=False)),
                ('col', models.IntegerField(blank=True, null=True)),
                ('gold_type', models.CharField(blank=True, max_length=1000)),
            ],
            options={
                'db_table': 'gold_annotation',
            },
        ),
        migrations.CreateModel(
            name='RecConcept',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('res_id', models.IntegerField()),
                ('table_id', models.IntegerField()),
                ('row_id', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('concept', models.CharField(max_length=255)),
                ('verdict', models.IntegerField()),
            ],
            options={
                'db_table': 'rec_concept',
            },
        ),
        migrations.CreateModel(
            name='TableCells',
            fields=[
                ('table_url', models.CharField(blank=True, max_length=500)),
                ('row', models.IntegerField(blank=True, null=True)),
                ('col', models.IntegerField(blank=True, null=True)),
                ('value', models.TextField(blank=True)),
                ('table_id', models.IntegerField(primary_key=True, serialize=False)),
                ('id', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'table_cells',
            },
        ),
        migrations.CreateModel(
            name='TableContext',
            fields=[
                ('table_url', models.CharField(blank=True, max_length=500)),
                ('content', models.TextField(blank=True)),
                ('table_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'table_context',
            },
        ),
        migrations.CreateModel(
            name='TableSchema',
            fields=[
                ('table_url', models.CharField(blank=True, max_length=500)),
                ('att_id', models.IntegerField(blank=True, null=True)),
                ('att_name', models.CharField(blank=True, max_length=2000)),
                ('att_type', models.CharField(blank=True, max_length=10)),
                ('is_entity', models.IntegerField(blank=True, null=True)),
                ('table_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'table_schema',
            },
        ),
        migrations.CreateModel(
            name='YagoConcept',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'yago_concept',
            },
        ),
        migrations.CreateModel(
            name='YagoEntity',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'yago_entity',
            },
        ),
        migrations.CreateModel(
            name='YagoType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('entity_id', models.IntegerField()),
                ('concept_id', models.IntegerField()),
            ],
            options={
                'db_table': 'yago_type',
            },
        ),
    ]
