# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 13:19
from __future__ import unicode_literals

from django.db import models, migrations

def load_tables_from_sql():
    from table_server.settings import BASE_DIR
    import os
    sql_statements = open(os.path.join(BASE_DIR, 'display/sql/table.sql'), 'r').readlines()

    return sql_statements


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(load_tables_from_sql()),
    ]
